### PR TITLE
awx: Remove clean-static-node and tox override

### PR DESCRIPTION
**Pull request by Spredzy**

### CODE REVIEW

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Pull request merged**
