### PR TITLE
zuul.d/projects.yaml: add community.elastic

### PR DESCRIPTION
**Pull request by Andersson007**
Merge after https://github.com/ansible/zuul-config/pull/497

Relates to https://github.com/ansible-collections/overview/issues/222

### CODE REVIEW

**Comment by Andersson007** [comment]
@jillr I've just rebased this PR so the collection is in both the files
```
./resources/ansible.yaml:        - ansible-collections/community.elastic:
./zuul.d/projects.yaml:    name: ansible-collections/community.elastic
```
but the error says that it's not in the main config file. I follow https://github.com/ansible/zuul-config#enable-the-github-application , is it still relevant?

**Comment by jillr** [comment]
I don't understand.  497 is merged and looks right as far as I can tell.  I'll try to think of something.  :/

**Comment by jillr** [comment]
I think what happened is that there was no build executed for 497, but there have been builds since then for other changes in ansible.yaml that included community.elastic as part of the config (see line 200 in resources/ansible.yaml in https://github.com/ansible/zuul-config/commit/acca43dcf0a67d5c23ef80aad9c340864be65830).

@goneri or @GomathiselviS  do either of you know how we get Zuul to reload config that should already be deployed, as far as I can tell?

**Comment by goneri** [comment]
For a reason I ignore, it looks like community.elastic is actually not in the project list: https://ansible.softwarefactory-project.io/zuul/projects

**Comment by goneri** [comment]
I just merged https://github.com/ansible/zuul-config/pull/502 which has triggered a config-update after the merge (c.f: https://ansible.softwarefactory-project.io/zuul/builds?job_name=config-update). Let's see if it's better now.

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
Sigh :-)

**Comment by goneri** [comment]
recheck

**Comment by Andersson007** [comment]
@jillr @goneri thanks a lot!

**Pull request merged**
