### PR TITLE
Try and force config update

### PR DESCRIPTION
**Pull request by gravesm**
Trying to force a config update with an inconsequential change to see if it will pass this time.

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
There is an issue with the config-update, in the logs `"msg": "Host parameter does not match hashed host field in supplied key"` : https://softwarefactory-project.io/zuul/t/ansible/build/2a41ab929f7242afbdf78dc72b13ae17

**Comment by gravesm** [comment]
I made another attempt in https://github.com/ansible/zuul-config/pull/582, but I don't really know what I'm doing. If you have any advice, I'd appreciate it.

**Comment by TristanCacqueray** [comment]
Thanks, that might work.

**Comment by TristanCacqueray** [comment]
it worked, well done!

**Pull request merged**
